version: "3.9"

services:
  dwh_pipeline:
    platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfile.dwh
    image: chrbigdatadev.azurecr.io/hr-pipeline:latest
    ports:
      - "3000:3000"

  dashboard:
    platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfile.dashboard
    image: chrbigdatadev.azurecr.io/dashboard:latest
    ports:
      - "8501:8501"