sources:
  - name: job_ads
    schema: staging
    tables:
      - name: stg_ads
        identifier: job_ads
        meta:
          dagster:
            asset_key: ["dlt_jobads_source_jobads_resource"]
